// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHE6_hUuYjHppZxkz5Zv4AM4uIpCqkaQ',
    appId: '1:903968291797:web:f06fad2c30109e169b5b5c',
    messagingSenderId: '903968291797',
    projectId: 'nodi-saar',
    authDomain: 'nodi-saar.firebaseapp.com',
    storageBucket: 'nodi-saar.firebasestorage.app',
    measurementId: 'G-5VD732DSXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZqnQgJJLuiODs3c5vb8F6QMZlZxol8s',
    appId: '1:903968291797:android:3322ed78c4dbe9e69b5b5c',
    messagingSenderId: '903968291797',
    projectId: 'nodi-saar',
    storageBucket: 'nodi-saar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEx3rvrf1awr_DvtRpQrDUPSfuerPIyK4',
    appId: '1:903968291797:ios:00554aca069cc1c79b5b5c',
    messagingSenderId: '903968291797',
    projectId: 'nodi-saar',
    storageBucket: 'nodi-saar.firebasestorage.app',
    iosBundleId: 'com.example.nodisaarV2',
  );
}
